### PR TITLE
core: envoy engine

### LINKED ISSUE #492: core/ios: crash when force-closing app with Envoy
When testing Envoy Mobile in an iOS TestFlight application, the user gets prompted with a modal from TestFlight saying that the Envoy-based app has crashed when the user force-closes the app by swiping it off screen. This is 100% reproducible.

Below is a stack trace from one of these crashes. Looks like we'll need to do a more graceful shutdown in these cases to prevent the OS from perceiving a crash (related: https://github.com/lyft/envoy-mobile/issues/445).

```
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.lyft.ios.alpha [1470]


Date/Time:           2019-10-04 11:29:44.8217 -0700
Launch Time:         2019-10-04 11:29:41.4918 -0700
OS Version:          iPhone OS 13.1.2 (17A860)
Release Type:        User
Baseband Version:    1.01.17
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Thread 0 name:
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001af350ef4 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x00000001af271d1c pthread_kill + 196 (pthread.c:1456)
2   libsystem_c.dylib             	0x00000001af201a54 abort + 104 (abort.c:110)
3   Lyft                          	0x0000000103803710 Envoy::ThreadLocal::InstanceImpl::shutdownGlobalThreading() + 172
4   Lyft                          	0x000000010380e044 Envoy::Server::InstanceImpl::terminate() + 52
5   Lyft                          	0x000000010380e918 Envoy::Server::InstanceImpl::~InstanceImpl() + 48
6   Lyft                          	0x000000010380ef58 Envoy::Server::InstanceImpl::~InstanceImpl() + 12
7   Lyft                          	0x0000000103755de4 Envoy::MainCommonBase::~MainCommonBase() + 40
8   Lyft                          	0x00000001037557f8 std::__1::unique_ptr<Envoy::MainCommon, std::__1::default_delete<Envoy::MainCommon> >::~unique_ptr() + 36
9   libsystem_c.dylib             	0x00000001af1e2048 __cxa_finalize_ranges + 416 (atexit.c:284)
10  libsystem_c.dylib             	0x00000001af1e2384 exit + 28 (exit.c:81)
11  UIKitCore                     	0x00000001b3600ce0 -[UIApplication _terminateWithStatus:] + 508 (UIApplication.m:6622)
12  UIKitCore                     	0x00000001b2da1df4 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionSto... + 128 (_UISceneLifecycleMultiplexer.m:765)
13  UIKitCore                     	0x00000001b2da1a50 -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 220 (_UISceneLifecycleMultiplexer.m:416)
14  UIKitCore                     	0x00000001b35f6fc0 -[UIApplication workspaceShouldExit:withTransitionContext:] + 216 (UIApplication.m:3658)
15  FrontBoardServices            	0x00000001b46c7b90 -[FBSUIApplicationWorkspaceShim workspaceShouldExit:withTransitionContext:] + 88 (FBSUIApplicationWorkspace.m:144)
16  FrontBoardServices            	0x00000001b46f5394 __83-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:withAcknowledgement:]_block_inv... + 80 (FBSWorkspaceScenesClient.m:281)
17  FrontBoardServices            	0x00000001b46da0f8 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 240 (FBSWorkspace.m:357)
18  FrontBoardServices            	0x00000001b46f5320 __83-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:withAcknowledgement:]_block_invoke + 140 (FBSWorkspaceScenesClient.m:278)
19  libdispatch.dylib             	0x00000001af20d00c _dispatch_client_callout + 20 (object.m:495)
20  libdispatch.dylib             	0x00000001af20fd50 _dispatch_block_invoke_direct + 264 (queue.c:463)
21  FrontBoardServices            	0x00000001b471c384 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 48 (FBSSerialQueue.m:173)
22  FrontBoardServices            	0x00000001b471c030 -[FBSSerialQueue _queue_performNextIfPossible] + 432 (FBSSerialQueue.m:216)
23  FrontBoardServices            	0x00000001b471c59c -[FBSSerialQueue _performNextFromRunLoopSource] + 32 (FBSSerialQueue.m:247)
24  CoreFoundation                	0x00000001af4e1260 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28 (CFRunLoop.c:1922)
25  CoreFoundation                	0x00000001af4e11b4 __CFRunLoopDoSource0 + 84 (CFRunLoop.c:1956)
26  CoreFoundation                	0x00000001af4e0920 __CFRunLoopDoSources0 + 184 (CFRunLoop.c:1992)
27  CoreFoundation                	0x00000001af4db7ec __CFRunLoopRun + 1068 (CFRunLoop.c:2882)
28  CoreFoundation                	0x00000001af4db098 CFRunLoopRunSpecific + 480 (CFRunLoop.c:3192)
29  GraphicsServices              	0x00000001b9645534 GSEventRunModal + 108 (GSEvent.c:2246)
30  UIKitCore                     	0x00000001b35fb7ac UIApplicationMain + 1940 (UIApplication.m:4753)
31  Lyft                          	0x0000000102bb76b0 main + 68
32  libdyld.dylib                 	0x00000001af35af30 start + 4

Thread 1:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 3 name:
Thread 3:
0   libsystem_kernel.dylib        	0x00000001af34ff48 __getattrlist + 8
1   CoreServicesInternal          	0x00000001b089adb4 GetattrlistRetry + 56 (DirEnum.c:629)
2   CoreServicesInternal          	0x00000001b089ac70 DirEnumOpen + 940 (DirEnum.c:869)
3   CoreServicesInternal          	0x00000001b0897b0c _InitalizeDirectoryEnumerator(_CFURLEnumerator*) + 1408 (FileURLEnumerator.cp:583)
4   CoreServicesInternal          	0x00000001b0896f0c _URLEnumeratorGetNextURL + 96 (FileURLEnumerator.cp:867)
5   CoreFoundation                	0x00000001af58e0a4 CFURLEnumeratorGetNextURL + 76 (CFURLEnumerator.c:27)
6   Foundation                    	0x00000001af87d9b8 -[NSFileManager contentsOfDirectoryAtURL:includingPropertiesForKeys:options:error:] + 248 (NSFileManager.m:2365)
7   Lyft                          	0x0000000105c434c0 Archiver.next(_:) + 1208
8   Lyft                          	0x0000000105c47cd0 Publisher.uploadNext() + 60
9   Lyft                          	0x0000000105c48fbc partial apply for closure #1 in Publisher.scheduleNextUpload(immediately:) + 64
10  Lyft                          	0x0000000105c49328 @objc ScheduledTask.main() + 88
11  Foundation                    	0x00000001af937fbc __NSOPERATION_IS_INVOKING_MAIN__ + 24 (NSOperation.m:2184)
12  Foundation                    	0x00000001af837464 -[NSOperation start] + 740 (NSOperation.m:2201)
13  Foundation                    	0x00000001af9389e8 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24 (NSOperation.m:2215)
14  Foundation                    	0x00000001af9384a8 __NSOQSchedule_f + 184 (NSOperation.m:2226)
15  libdispatch.dylib             	0x00000001af20bbb0 _dispatch_call_block_and_release + 32 (init.c:1408)
16  libdispatch.dylib             	0x00000001af20d00c _dispatch_client_callout + 20 (object.m:495)
17  libdispatch.dylib             	0x00000001af20f78c _dispatch_continuation_pop + 408 (inline_internal.h:2487)
18  libdispatch.dylib             	0x00000001af20eeec _dispatch_async_redirect_invoke + 596 (queue.c:800)
19  libdispatch.dylib             	0x00000001af21bbd4 _dispatch_root_queue_drain + 348 (inline_internal.h:2528)
20  libdispatch.dylib             	0x00000001af21c384 _dispatch_worker_thread2 + 120 (queue.c:6569)
21  libsystem_pthread.dylib       	0x00000001af272a60 _pthread_wqthread + 216 (pthread.c:2336)
22  libsystem_pthread.dylib       	0x00000001af278c78 start_wqthread + 8

Thread 4 name:
Thread 4:
0   libsystem_kernel.dylib        	0x00000001af32ebc4 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001af32dfe0 mach_msg + 76 (mach_msg.c:103)
2   CoreFoundation                	0x00000001af4e0abc __CFRunLoopServiceMachPort + 220 (CFRunLoop.c:2575)
3   CoreFoundation                	0x00000001af4db954 __CFRunLoopRun + 1428 (CFRunLoop.c:2931)
4   CoreFoundation                	0x00000001af4db098 CFRunLoopRunSpecific + 480 (CFRunLoop.c:3192)
5   Foundation                    	0x00000001af820580 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232 (NSRunLoop.m:374)
6   Foundation                    	0x00000001af820458 -[NSRunLoop(NSRunLoop) runUntilDate:] + 92 (NSRunLoop.m:421)
7   UIKitCore                     	0x00000001b3696668 -[UIEventFetcher threadMain] + 156 (UIEventFetcher.m:637)
8   Foundation                    	0x00000001af81f1e4 -[NSThread main] + 40 (NSThread.m:760)
9   Foundation                    	0x00000001af95aa84 __NSThread__start__ + 852 (NSThread.m:724)
10  libsystem_pthread.dylib       	0x00000001af270d5c _pthread_start + 128 (pthread.c:895)
11  libsystem_pthread.dylib       	0x00000001af278c84 thread_start + 8

Thread 5 name:
Thread 5:
0   libsystem_kernel.dylib        	0x00000001af352e84 necp_client_action + 8
1   libnetwork.dylib              	0x00000001b1b61dd0 nw_path_flow_registration_set_ecn_cache + 176 (path_evaluation.m:4758)
2   libusrtcp.dylib               	0x00000001b487d354 tcp_input + 13876 (tcp_cache.c:220)
3   libusrtcp.dylib               	0x00000001b4898d88 __tcp_input_available_block_invoke + 60 (user_socket.c:1622)
4   libusrtcp.dylib               	0x00000001b4898be4 tcp_input_available + 676 (frame_internal.h:1079)
5   libusrtcp.dylib               	0x00000001b486e320 nw_protocol_tcp_input_available + 224 (protocol_tcp.c:1867)
6   libnetwork.dylib              	0x00000001b18ab054 nw_protocol_default_input_available + 72 (protocol_default.c:67)
7   libnetwork.dylib              	0x00000001b198d2f8 nw_channel_add_input_frames + 4332 (channel.c:1121)
8   libnetwork.dylib              	0x00000001b198c190 nw_channel_update_input_source + 172 (channel.c:1195)
9   libnetwork.dylib              	0x00000001b198b9a0 __nw_channel_create_block_invoke.32 + 56 (channel.c:2056)
10  libdispatch.dylib             	0x00000001af20d00c _dispatch_client_callout + 20 (object.m:495)
11  libdispatch.dylib             	0x00000001af20f78c _dispatch_continuation_pop + 408 (inline_internal.h:2487)
12  libdispatch.dylib             	0x00000001af21ff18 _dispatch_source_invoke2 + 892 (source.c:568)
13  libdispatch.dylib             	0x00000001af21f8c4 _dispatch_source_invoke + 428 (inline_internal.h:1854)
14  libdispatch.dylib             	0x00000001af215004 _dispatch_workloop_invoke2 + 572 (inline_internal.h:2528)
15  libdispatch.dylib             	0x00000001af214b20 _dispatch_workloop_invoke + 428 (inline_internal.h:1854)
16  libdispatch.dylib             	0x00000001af21cf20 _dispatch_workloop_worker_thread + 580 (queue.c:6386)
17  libsystem_pthread.dylib       	0x00000001af272aa0 _pthread_wqthread + 280 (pthread.c:2323)
18  libsystem_pthread.dylib       	0x00000001af278c78 start_wqthread + 8

Thread 6:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 7:
0   libsystem_kernel.dylib        	0x00000001af3529d4 kevent + 8
1   Lyft                          	0x0000000103a821cc kq_dispatch + 572
2   Lyft                          	0x0000000103a7c408 event_base_loop + 988
3   Lyft                          	0x0000000103812374 Envoy::Server::InstanceImpl::run() + 532
4   Lyft                          	0x00000001037763d8 Envoy::MainCommonBase::run() + 64
5   Lyft                          	0x0000000103755b8c run_engine + 404
6   Lyft                          	0x00000001037531cc -[EnvoyEngineImpl runWithConfigYAML:logLevel:] + 140
7   Lyft                          	0x00000001037530d4 -[EnvoyEngineImpl runWithConfig:logLevel:] + 204
8   Lyft                          	0x0000000103739e0c EnvoyClient.RunnerThread.main() + 600
9   Lyft                          	0x0000000103739e68 @objc EnvoyClient.RunnerThread.main() + 48
10  Foundation                    	0x00000001af95aa84 __NSThread__start__ + 852 (NSThread.m:724)
11  libsystem_pthread.dylib       	0x00000001af270d5c _pthread_start + 128 (pthread.c:895)
12  libsystem_pthread.dylib       	0x00000001af278c84 thread_start + 8

Thread 8 name:
Thread 8:
0   libsystem_kernel.dylib        	0x00000001af32ebc4 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001af32dfe0 mach_msg + 76 (mach_msg.c:103)
2   libsystem_kernel.dylib        	0x00000001af34b298 thread_suspend + 84 (thread_actUser.c:1016)
3   Lyft                          	0x000000010446ae58 ksmachexc_i_handleExceptions + 100
4   libsystem_pthread.dylib       	0x00000001af270d5c _pthread_start + 128 (pthread.c:895)
5   libsystem_pthread.dylib       	0x00000001af278c84 thread_start + 8

Thread 9 name:
Thread 9:
0   libsystem_kernel.dylib        	0x00000001af32ebc4 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001af32dfe0 mach_msg + 76 (mach_msg.c:103)
2   Lyft                          	0x000000010446ae7c ksmachexc_i_handleExceptions + 136
3   libsystem_pthread.dylib       	0x00000001af270d5c _pthread_start + 128 (pthread.c:895)
4   libsystem_pthread.dylib       	0x00000001af278c84 thread_start + 8

Thread 10:
0   libsystem_kernel.dylib        	0x00000001af3529d4 kevent + 8
1   Lyft                          	0x0000000103a821cc kq_dispatch + 572
2   Lyft                          	0x0000000103a7c408 event_base_loop + 988
3   Lyft                          	0x0000000103a62fec Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>)::$_0::__invoke(void*) + 28
4   libsystem_pthread.dylib       	0x00000001af270d5c _pthread_start + 128 (pthread.c:895)
5   libsystem_pthread.dylib       	0x00000001af278c84 thread_start + 8

Thread 11:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 12:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 13:
0   libsystem_kernel.dylib        	0x00000001af3529d4 kevent + 8
1   Lyft                          	0x0000000103a821cc kq_dispatch + 572
2   Lyft                          	0x0000000103a7c408 event_base_loop + 988
3   Lyft                          	0x00000001038477a4 Envoy::Server::WorkerImpl::threadRoutine(Envoy::Server::GuardDog&) + 240
4   Lyft                          	0x0000000103a62fec Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>)::$_0::__invoke(void*) + 28
5   libsystem_pthread.dylib       	0x00000001af270d5c _pthread_start + 128 (pthread.c:895)
6   libsystem_pthread.dylib       	0x00000001af278c84 thread_start + 8

Thread 14:
0   libsystem_kernel.dylib        	0x00000001af3529d4 kevent + 8
1   Lyft                          	0x0000000103a821cc kq_dispatch + 572
2   Lyft                          	0x0000000103a7c408 event_base_loop + 988
3   Lyft                          	0x00000001038477a4 Envoy::Server::WorkerImpl::threadRoutine(Envoy::Server::GuardDog&) + 240
4   Lyft                          	0x0000000103a62fec Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>)::$_0::__invoke(void*) + 28
5   libsystem_pthread.dylib       	0x00000001af270d5c _pthread_start + 128 (pthread.c:895)
6   libsystem_pthread.dylib       	0x00000001af278c84 thread_start + 8

Thread 15:
0   libsystem_kernel.dylib        	0x00000001af3529d4 kevent + 8
1   Lyft                          	0x0000000103a821cc kq_dispatch + 572
2   Lyft                          	0x0000000103a7c408 event_base_loop + 988
3   Lyft                          	0x00000001038477a4 Envoy::Server::WorkerImpl::threadRoutine(Envoy::Server::GuardDog&) + 240
4   Lyft                          	0x0000000103a62fec Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>)::$_0::__invoke(void*) + 28
5   libsystem_pthread.dylib       	0x00000001af270d5c _pthread_start + 128 (pthread.c:895)
6   libsystem_pthread.dylib       	0x00000001af278c84 thread_start + 8

Thread 16:
0   libsystem_kernel.dylib        	0x00000001af3529d4 kevent + 8
1   Lyft                          	0x0000000103a821cc kq_dispatch + 572
2   Lyft                          	0x0000000103a7c408 event_base_loop + 988
3   Lyft                          	0x00000001038477a4 Envoy::Server::WorkerImpl::threadRoutine(Envoy::Server::GuardDog&) + 240
4   Lyft                          	0x0000000103a62fec Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>)::$_0::__invoke(void*) + 28
5   libsystem_pthread.dylib       	0x00000001af270d5c _pthread_start + 128 (pthread.c:895)
6   libsystem_pthread.dylib       	0x00000001af278c84 thread_start + 8

Thread 17:
0   libsystem_kernel.dylib        	0x00000001af3529d4 kevent + 8
1   Lyft                          	0x0000000103a821cc kq_dispatch + 572
2   Lyft                          	0x0000000103a7c408 event_base_loop + 988
3   Lyft                          	0x00000001038477a4 Envoy::Server::WorkerImpl::threadRoutine(Envoy::Server::GuardDog&) + 240
4   Lyft                          	0x0000000103a62fec Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>)::$_0::__invoke(void*) + 28
5   libsystem_pthread.dylib       	0x00000001af270d5c _pthread_start + 128 (pthread.c:895)
6   libsystem_pthread.dylib       	0x00000001af278c84 thread_start + 8

Thread 18:
0   libsystem_kernel.dylib        	0x00000001af3529d4 kevent + 8
1   Lyft                          	0x0000000103a821cc kq_dispatch + 572
2   Lyft                          	0x0000000103a7c408 event_base_loop + 988
3   Lyft                          	0x00000001038477a4 Envoy::Server::WorkerImpl::threadRoutine(Envoy::Server::GuardDog&) + 240
4   Lyft                          	0x0000000103a62fec Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>)::$_0::__invoke(void*) + 28
5   libsystem_pthread.dylib       	0x00000001af270d5c _pthread_start + 128 (pthread.c:895)
6   libsystem_pthread.dylib       	0x00000001af278c84 thread_start + 8

Thread 19 name:
Thread 19:
0   libsystem_kernel.dylib        	0x00000001af32ebc4 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001af32dfe0 mach_msg + 76 (mach_msg.c:103)
2   CoreFoundation                	0x00000001af4e0abc __CFRunLoopServiceMachPort + 220 (CFRunLoop.c:2575)
3   CoreFoundation                	0x00000001af4db954 __CFRunLoopRun + 1428 (CFRunLoop.c:2931)
4   CoreFoundation                	0x00000001af4db098 CFRunLoopRunSpecific + 480 (CFRunLoop.c:3192)
5   CFNetwork                     	0x00000001b279dbc8 -[__CoreSchedulingSetRunnable runForever] + 192 (CoreSchedulingSet.mm:1372)
6   Foundation                    	0x00000001af81f1e4 -[NSThread main] + 40 (NSThread.m:760)
7   Foundation                    	0x00000001af95aa84 __NSThread__start__ + 852 (NSThread.m:724)
8   libsystem_pthread.dylib       	0x00000001af270d5c _pthread_start + 128 (pthread.c:895)
9   libsystem_pthread.dylib       	0x00000001af278c84 thread_start + 8

Thread 20:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 21:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 22:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 23:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 24:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 25:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 26 name:
Thread 26:
0   libsystem_kernel.dylib        	0x00000001af32ebc4 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001af32dfe0 mach_msg + 76 (mach_msg.c:103)
2   CoreFoundation                	0x00000001af4e0abc __CFRunLoopServiceMachPort + 220 (CFRunLoop.c:2575)
3   CoreFoundation                	0x00000001af4db954 __CFRunLoopRun + 1428 (CFRunLoop.c:2931)
4   CoreFoundation                	0x00000001af4db098 CFRunLoopRunSpecific + 480 (CFRunLoop.c:3192)
5   Foundation                    	0x00000001af820580 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232 (NSRunLoop.m:374)
6   Lyft                          	0x000000010330ffac -[GMSx_GTMSimpleWorkerThread main] + 184
7   Foundation                    	0x00000001af95aa84 __NSThread__start__ + 852 (NSThread.m:724)
8   libsystem_pthread.dylib       	0x00000001af270d5c _pthread_start + 128 (pthread.c:895)
9   libsystem_pthread.dylib       	0x00000001af278c84 thread_start + 8

Thread 27 name:
Thread 27:
0   libsystem_kernel.dylib        	0x00000001af351180 __select + 8
1   CoreFoundation                	0x00000001af4ee90c __CFSocketManager + 628 (CFSocket.c:1321)
2   libsystem_pthread.dylib       	0x00000001af270d5c _pthread_start + 128 (pthread.c:895)
3   libsystem_pthread.dylib       	0x00000001af278c84 thread_start + 8

Thread 28:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 29:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 30:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 31:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 32:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 33:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 34:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 35:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 36:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 37:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 38:
0   libsystem_pthread.dylib       	0x00000001af278c70 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x000000010c32a740   x5: 0x0000000000000029   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x00000001078b5840   x9: 0x00000000091c3400  x10: 0x0000000000000000  x11: 0x0000000000000002
   x12: 0x0000000000000002  x13: 0x0000000000000000  x14: 0x0000000017c00000  x15: 0x0000000017c007fc
   x16: 0x0000000000000148  x17: 0x00000001ecc62f10  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000000000407  x21: 0x00000001078b5920  x22: 0x000000010901b600  x23: 0x0000000000000000
   x24: 0x0000000000000008  x25: 0x00000001f7985000  x26: 0x000000000000001d  x27: 0x0000000000000002
   x28: 0x0000000000000010   fp: 0x000000016d67e4c0   lr: 0x00000001af271d1c
    sp: 0x000000016d67e4a0   pc: 0x00000001af350ef4 cpsr: 0x40000000
   esr: 0x56000080  Address size fault
```

### PR DESCRIPTION
**Pull request by goaway**
Description: create a class to manage Envoy lifecycle and allow for graceful teardown. Teardown is now graceful for both iOS and Android. Envoy's codebase expects to have shutdown happen from the main thread. However, in mobile the thread the engine runs in is not the main thread of the process, and thus shutdown/destructors were not getting run from the thread the engine was started on. This PR makes sure that the engine is destructed/shutdown from the thread that it ran in.
Risk Level: high. This PR changes state management for the engine, and initializes it on a std::thread instead of a platform thread. iOS thread management is afaict handled gracefully. On Android the native thread has to be attached and detached from the JVM. This PR attaches the native thread, but the work to detach is a bit involved so will come in a subsequent PR.
Testing: local device testing.

Fixes #492 

Co-authored-by: Jose Nino <jnino@lyft.com>
Signed-off-by: Mike Schore <mike.schore@gmail.com>

### CODE REVIEW

File: library/common/jni_interface.cc [hunk 1]
```diff
@@ -121,6 +119,11 @@ static JNIEnv* get_env() {
   int get_env_res = static_jvm->GetEnv((void**)&env, JNI_VERSION);
   if (get_env_res == JNI_EDETACHED) {
     __android_log_write(ANDROID_LOG_ERROR, "jni_lib", "equals JNI_EDETACHED");
+    // Note: the only thread that should need to be attached is Envoy's engine std::thread.
+    // TODO: harden this piece of code to make sure that we are only needing to attach Envoy
+    // engine's std::thread, and that we detach it successfully.
+    static_jvm->AttachCurrentThread(&env, NULL);
```
Comment (junr03) [inline library/common/jni_interface.cc]: I am going to add thread detachment in a subsequent PR, as it requires introducing engine level callbacks. I don't want to make this PR any bigger.

File: library/common/engine.cc [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+    Thread::LockGuard lock(mutex_);
+    try {
+      char* envoy_argv[] = {strdup("envoy"), strdup("--config-yaml"),   strdup(config.c_str()),
+                            strdup("-l"),    strdup(log_level.c_str()), nullptr};
+
+      main_common_ = std::make_unique<Envoy::MainCommon>(5, envoy_argv);
+      event_dispatcher_ = &main_common_->server()->dispatcher();
+      cv_.notifyOne();
+    } catch (const Envoy::NoServingException& e) {
+      return ENVOY_SUCCESS;
```
Comment (buildbreaker) [inline library/common/engine.cc]: What makes `NoServingException` a successful run?

File: library/common/main_interface.cc [hunk 3]
```diff
@@ -67,62 +51,7 @@ envoy_status_t set_preferred_network(envoy_network_t network) {
...
-  } catch (const Envoy::EnvoyException& e) {
-    std::cerr << e.what() << std::endl;
-    return ENVOY_FAILURE;
-  }
-
-  // Run the server listener loop outside try/catch blocks, so that unexpected
-  // exceptions show up as a core-dumps for easier diagnostics.
-  return main_common_->run() ? ENVOY_SUCCESS : ENVOY_FAILURE;
+envoy_status_t run_engine(envoy_engine_t, const char* config, const char* log_level) {
+  engine_ = std::make_unique<Envoy::Engine>(config, log_level, preferred_network_);
```
Comment (rebello95) [inline library/common/main_interface.cc]: Might be good to link an issue for making Envoy instance-based rather than an `engine_` singleton here

Comment (goaway) [reply library/common/main_interface.cc]: We do have an existing issue, and it's referenced above on L42. But we could reference it here as well.

**Comment by goaway** [comment]
@junr03 just posting to say I think the updates you've made look good. 👍

**Comment by rebello95** [comment]
Can we mention that this resolves https://github.com/lyft/envoy-mobile/issues/492 in the PR description and close out that issue when this merges? 😃

**Comment by junr03** [comment]
> Can we mention that this resolves #492 in the PR description and close out that issue when this merges? 😃

I wanted to to that in #507 as that completes the work for the crash 100%. It also completes work for #445. Does that sound good?

**Comment by rebello95** [comment]
Sure, SGTM

**Comment by goaway** [comment]
Hm. I do think I'd suggest that this PR more directly addresses #492, and is probably the most relevant if we're ever looking for that commit.

**Comment by junr03** [comment]
Sure, I can add it here.

File: library/common/jni_interface.cc (hunk 1 above)
Comment (mattklein123) [inline library/common/jni_interface.cc]: nit: s/NULL/nullptr

Comment (junr03) [reply library/common/jni_interface.cc]: will do in subsequent PR to avoid re-approval and re-running CI

Comment (junr03) [reply library/common/jni_interface.cc]: https://github.com/lyft/envoy-mobile/pull/507/files#diff-87fca06766521056096d5a45653f1aebR135
