### PR TITLE
shutdown: create avenues for shutdown out of static de-initialization

### LINKED ISSUE #831: crash: trying to use garbage/null pointer
Stacktrace:

```
# (sometimes a garbage pointer)
EXC_BAD_ACCESS: Attempted to dereference null pointer. 

0  Lyft                    Envoy::Http::Dispatcher::post(std::__1::function<void ()>) (Lyft)
1  Lyft                    Envoy::Http::Dispatcher::startStream(long, envoy_http_callbacks) (Lyft)
2  Lyft                    start_stream (Lyft)
3  Lyft                    -[EnvoyHTTPStreamImpl initWithHandle:callbacks:] (Lyft)
4  Lyft                    -[EnvoyEngineImpl startStreamWithCallbacks:] (Lyft)
```

The only pointer accessed in `Http::Dispatcher::post` is the `event_dispatcher_` pointer here: 

https://github.com/lyft/envoy-mobile/blob/5c01e711e70c80c101087e61722862cbfbe961c9/library/common/http/dispatcher.cc#L282

The pointer is correctly initialized to nullptr, set by an initialization callback, and guarded by synchronization mechanisms. So I believe the crash is happening because the `Event::Dispatcher` the pointer points to is getting deallocated.

That `Event::Dispatcher` is uniquely owned by the `Server::InstanceImpl`. Which in turn (through some layers of inner classes ends up uniquely owned by `main_common_` in the Envoy Mobile codebase. The only code path where that unique pointer is reset is when the event loop exits here: 

https://github.com/lyft/envoy-mobile/blob/5c01e711e70c80c101087e61722862cbfbe961c9/library/common/engine.cc#L84

The only place where Envoy Mobile explicitly exits the event loop is in the Engine destructor: 

https://github.com/lyft/envoy-mobile/blob/5c01e711e70c80c101087e61722862cbfbe961c9/library/common/engine.cc#L104

Currently envoy mobile has only a singleton engine that is statically instantiated. Therefore, Envoy Mobile should not be exiting the event loop unless the app is quitting, or has otherwise crashed causing static deallocation. However, from the stacktrace above it looks like:

a) The event loop has exited, causing` main_common_` to be reset and the `event_dispatcher_` pointer to become garbage
b) The exit is happening without the static Engine singleton being destroyed, as evidenced by the fact that the stack trace above is able to lock the Engine's weak pointer.

I have created a [test case](https://github.com/lyft/envoy-mobile/blob/set-null/test/common/engine_test.cc#L10) where I force event loop exit and subsequently use the engine, resulting in a repro where the `event_dispatcher_` is garbage.

## Open Question

My remaining unknown is: why is the event loop exiting without the Envoy Mobile code calling `exit()` on it. My only theory is that Envoy runs the event loop with `Event::Dispatcher::RunType::Block` 

https://github.com/envoyproxy/envoy/blob/c2a63735145ef1ce056ca2a50927e3e6682177eb/source/server/server.cc#L592

Which is described as `// Runs the event-loop until there are no pending events.`All of the crashes show that the app had been sent to the background (and afaict the crash is only happening in iOS). So I am wondering somehow the event loop is exiting prematurely I would assume that pending timers for stats flushes, timeouts, should keep the event loop running given that there are pending events. I am not a libevent or iOS expert, but I am wondering if on mobile libevent behaves differently, and exits under some conditions which does not happen on the server.

One idea I have is to allow users of the `Server::InstanceImpl` to dictate how the event loop is run, and run it with `Event::Dispatcher::RunType::Block`

@Reflejo @mattklein123 I investigated this yesterday afternoon, I would appreciate if you could give it a read, and let me know what you think. @Reflejo specially around the theory of iOS causing the libevent loop to exit prematurely.

### PR DESCRIPTION
**Pull request by junr03**
Description: this PR attempts to fix two related crashes. By hooking up to iOS's notification system we attempt to terminate the engine earlier, and allow all objects necessary to be available fixing #1035. Potentially fixes #831.
Risk Level: med - changes termination sequence
Testing: added test

Signed-off-by: Jose Nino <jnino@lyft.com>

### CODE REVIEW

File: library/common/engine.cc [hunk 1]
```diff
@@ -21,17 +21,21 @@ Engine::Engine(envoy_engine_callbacks callbacks, const char* config, const char*
...
   {
     Thread::LockGuard lock(mutex_);
     try {
-      char* envoy_argv[] = {strdup("envoy"), strdup("--config-yaml"),   strdup(config.c_str()),
-                            strdup("-l"),    strdup(log_level.c_str()), nullptr};
+      const std::string name = "envoy";
+      const std::string config_flag = "--config-yaml";
+      const std::string log_flag = "-l";
+      const char* envoy_argv[] = {name.c_str(),     config_flag.c_str(), config.c_str(),
+                                  log_flag.c_str(), log_level.c_str(),   nullptr};
```
Comment (goaway) [inline library/common/engine.cc:32]: Can you provide some motivation here?

File: library/common/engine.cc [hunk 2]
```diff
@@ -60,13 +64,14 @@ envoy_status_t Engine::run(std::string config, std::string log_level) {
...
 
-  // The above call is blocking; at this point the event loop has exited.
-  callbacks_.on_exit();
-
   // Ensure destructors run on Envoy's main thread.
+  http_dispatcher_->exit();
   postinit_callback_handler_.reset();
   TS_UNCHECKED_READ(main_common_).reset();
 
+  // The above call is blocking; at this point the event loop has exited.
```
Comment (goaway) [inline library/common/engine.cc:72]: This comment really applies to the event loop rather than the above calls now.

File: library/common/engine.cc (hunk 1 above)
Comment (junr03) [reply library/common/engine.cc:32]: asan correctly complained about the engine test. the old strdup based implementation was leaking all these strings.

**Comment by junr03** [comment]
@goaway any more comments here?

File: library/objective-c/EnvoyEngineImpl.m [hunk 3]
```diff
@@ -193,19 +195,18 @@ - (void)recordCounter:(NSString *)elements count:(NSUInteger)count {
...
 }
 
 - (void)lifecycleDidChangeWithNotification:(NSNotification *)notification {
-  NSLog(@"[Envoy] triggering stats flush (%@)", notification.name);
-  flush_stats();
+  NSLog(@"[Envoy] terminating engine (%@)", notification.name);
+  // TODO: ensure this is called with the correct envoy_engine_t once multiple Engine objects can
+  // be allocated.
+  // https://github.com/lyft/envoy-mobile/issues/332
+  terminate_engine(0);
```
Comment (goaway) [inline library/objective-c/EnvoyEngineImpl.m:209]: Won't this terminate the engine on _any_ lifecycle notification? Or are we only registering for backgrounding/shutdown.

Comment (goaway) [reply library/objective-c/EnvoyEngineImpl.m:209]: Also, we should have access to the engine handle here. No need to hardcode `0`.

File: library/common/engine.cc [hunk 4]
```diff
@@ -60,14 +64,14 @@ envoy_status_t Engine::run(std::string config, std::string log_level) {
...
   bool run_success = TS_UNCHECKED_READ(main_common_)->run();
-
   // The above call is blocking; at this point the event loop has exited.
-  callbacks_.on_exit();
 
   // Ensure destructors run on Envoy's main thread.
   postinit_callback_handler_.reset();
   TS_UNCHECKED_READ(main_common_).reset();
 
+  callbacks_.on_exit(callbacks_.context);
```
Comment (goaway) [inline library/common/engine.cc:73]: I agree this ordering makes more sense.

File: library/objective-c/EnvoyEngineImpl.m (hunk 3 above)
Comment (junr03) [reply library/objective-c/EnvoyEngineImpl.m:209]: I deleted the observer for `UIApplicationWillResignActiveNotification` so it will only be on termination. ack on the engine handle, will update.

**Comment by junr03** [comment]
@goaway updated!

**Comment by junr03** [comment]
btw https://github.com/lyft/envoy-mobile/runs/1064413662 effectively repros the crash prior to #1067. Merging main to include #1067 gives me a green test 🎉

File: library/objective-c/EnvoyEngineImpl.m (hunk 3 above)
Comment (goaway) [reply library/objective-c/EnvoyEngineImpl.m]: I think the notification actually has the lifecycle event on it, so we could be more picky here. My worry is that if someone adds it back in, it won't be obvious they're doing something wrong, and it could cause networking to fail until the app is restarted.

File: library/common/engine.cc (hunk 1 above)
Comment (goaway) [reply library/common/engine.cc:32]: We were leaking them intentionally before because we weren't sure how long Envoy needed them to stick around. This is fine though; they're on the stack anyways for the full duration of `run`.

**Review by goaway — APPROVED** [review]

**Review by goaway — APPROVED** [review]
